version: '3.8'

services:

  web:
    build: .
    ports:
      - "8080:80"

    environment:
      DB_HOST: db
      DB_NAME: inviteme
      DB_USER: root
      DB_PASSWORD: root

    depends_on:
      - db

  db:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inviteme

    ports:
      - "3306:3306"